---
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: containers/app/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    volumes:
      - .:/var/www/html:rw
